name: Deploy frontend
on:
  push:
    branches:
      - master
jobs:
  gae-deploy:
    name: Build & deploy to Google App Engine
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v3

      - id: nodejs
        name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - id: npm-deps
        name: Install deps
        run: npm ci

      - id: build
        name: Build
        run: npm run build

      - id: env-config
        name: Env config
        env:
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: envsubst < app.yaml.tpl > app.yaml

      - id: gcp-auth
        name: GCP Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: deploy
        name: Deploy
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          working_directory: packages/frontend
