name: Deploy frontend
on:
  push:
    branches:
      - master
jobs:
  gae-deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: Deploy
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          working_directory: "packages/frontend"
