name: Deploy frontend
on:
  push:
    branches:
      - main
jobs:
  gae-deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    environment: test
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          working_directory: "packages/frontend"
